[package]
name = "mgk-perps-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
doctest = false

[dependencies]
pinocchio = { workspace = true }
pinocchio-pubkey = { workspace = true }
mgk-common = { path = "../common" }
sha2 = { version = "0.10", optional = true }

[features]
default = []
bpf-entrypoint = []
test-sbf = []
host-hash = ["sha2"]

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
mgk-perps-matcher = { path = "../perps-matcher" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
